{% set name = "scanspec" %}
{% set version = "0.10.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scanspec-{{ version }}.tar.gz
  sha256: 8d0d93c4b5a3c74d983a38c6f6001d3cc574429a7a26604a31a61b82c373f0a9

build:
  entry_points:
    - scanspec = scanspec.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - click >=8.1
    - pydantic >=2.0

test:
  imports:
    - scanspec
  commands:
    - pip check
    - scanspec --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/bluesky/scanspec
  summary: Specify step and flyscan paths in a serializable, efficient and Pythonic way
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jwlodek
